<table id="<%=strCId%>${ctrl.name}" 
	data-search="true"
	data-show-refresh="true"
	data-show-toggle="true"
	data-show-columns="true"
	data-show-export="true"
	data-detail-view="true"
	data-detail-formatter="detailFormatter"
	data-minimum-count-columns="2"
	data-show-pagination-switch="true"
	data-pagination="true"
	data-page-list="[10, 25, 50, 100, ALL]"
	data-show-footer="true"
	data-side-pagination="server"
	>
</table>